# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'flutter_to_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  flutter_application_path = '../my_flutter'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  # Pods for flutter_to_ios
   install_all_flutter_pods(flutter_application_path)

  target 'flutter_to_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'flutter_to_iosUITests' do
    # Pods for testing
  end

end


post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end